name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: airg
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=5
      redis:
        image: redis:7
        ports: ["6379:6379"]
      nats:
        image: nats:2
        ports: ["4222:4222", "8222:8222"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install JS deps
        run: npm install

      - name: Lint & Type-check (frontend)
        run: npm run lint --workspace=frontend && npm run type-check --workspace=frontend

      - name: Lint & Type-check (api)
        run: npm run lint --workspace=api && npm run type-check --workspace=api

      - name: Run JS tests
        run: npm test --workspaces --if-present

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          pip install -U pip
          cd workers
          pip install -e .[dev]

      - name: Lint Python
        run: |
          cd workers
          ruff check .
          mypy .

      - name: Test Python
        run: |
          cd workers
          pytest -q

